### ISSUE TITLE
ErrorException : "Undefined index: title"

### ISSUE THREAD

**Issue by mathieutu** [uxweb/sweet-alert#27]
Hi!
Just to tell you that when you use the persistent() options before setting a message (and so a title),
we've got an error:

```
[2016-07-05 10:57:35] local.ERROR: exception 'ErrorException' with message 'Undefined index: title' in /usr/share/nginx/html/vendor/uxweb/sweet-alert/src/SweetAlert/SweetAlertNotifier.php:224
Stack trace:
#0 /usr/share/nginx/html/vendor/uxweb/sweet-alert/src/SweetAlert/SweetAlertNotifier.php(224): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/usr/share/ngin...', 224, Array)
#1 /usr/share/nginx/html/vendor/uxweb/sweet-alert/src/SweetAlert/SweetAlertNotifier.php(199): UxWeb\SweetAlert\SweetAlertNotifier->hasTitle()
#2 /usr/share/nginx/html/vendor/uxweb/sweet-alert/src/SweetAlert/SweetAlertNotifier.php(189): UxWeb\SweetAlert\SweetAlertNotifier->buildConfig()
#3 /usr/share/nginx/html/vendor/uxweb/sweet-alert/src/SweetAlert/SweetAlertNotifier.php(173): UxWeb\SweetAlert\SweetAlertNotifier->flashConfig()
#4 /usr/share/nginx/html/app/Http/Middleware/CanAccess.php(25): UxWeb\SweetAlert\SweetAlertNotifier->persistent()
```

Thanks!

**Comment by uxweb** [comment]
@mathieutu 

Thanks man, looks like i have to set an empty string as default for the alert title and alert message to prevent this :).

Will be fixed in the next release!
